const KEY_KEEP_ON_SCREEN = 'KEY_KEEP_ON_SCREEN';
const KEY_KEEP_ON_STYLE = 'KEY_KEEP_ON_STYLE';
const KEY_ADD_DOWNLOAD = 'KEY_ADD_DOWNLOAD';
const RELOAD_DETAIL = 'RELOAD_DETAIL';
const KEY_SETUP_WEAK_LOCK = 'KEY_SETUP_WEAK_LOCK';
const GET_PATH_FILE = 'GET_PATH_FILE';
const START_SCAN = 'START_SCAN';
const OPEN_RATE_APP = 'OPEN_RATE_APP';
const KEY_CLICK_REVIEW = 'KEY_CLICK_REVIEW';
const KEY_DATE_TIME = 'KEY_DATE_TIME';
const String PATH_GET_KEY_LANGUAGE = 'https://portal.123dok.com/api/language/list';
const String PATH_GET_LANGUAGE = 'https://portal.123dok.com/api/language/export';

const KEY_HOME_CONTROLLER_INITTIAL = 'KEY_HOME_CONTROLLER_INITTIAL';
